--- 
author: Ricardo Signes <rjbs@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Mail-SpamAssassin-SimpleClient
no_index: 
  directory: 
    - inc
    - t
requires: 
  Email::MIME: 1
  Mail::SpamAssassin: 3
version: 0.002
